### ISSUE TITLE
构建了适用于1.19的模组文件

### ISSUE THREAD

**Issue by czruby** [AnzhiZhang/MCDRCommandFabric#2]
修改了过时的方法，重新构建了适用于1.19版本的模组文件
https://github.com/czruby/MCDRCommandFabric

**Comment by AnzhiZhang** [comment]
能否详细描述作了哪些修改？

**Comment by czruby** [comment]
主要就是这两个文件https://github.com/czruby/MCDRCommandFabric/blob/1.19/src/main/java/com/czruby/mcdrcommand/fabric/MCDRCommand.java
https://github.com/czruby/MCDRCommandFabric/blob/1.19/src/main/java/com/czruby/mcdrcommand/fabric/CommonCommandHandler.java
一些方法的api版本升级了

**Comment by czruby** [comment]
您能否新建一个分支，我把新版本的提交上去

**Comment by AnzhiZhang** [comment]
已新建

**Comment by AnzhiZhang** [comment]
clase via https://github.com/AnzhiZhang/MCDRCommandFabric/commit/be8963962744e7d9c3dc6128f37730900c532766
