### ISSUE TITLE
希望能够适配其他平台

### ISSUE THREAD

**Issue by MC-Nirvana** [AnzhiZhang/MCDRCommandFabric#9]
希望能够适配其他平台（例如Forge、NeoForge和Spigot），信雅互联虽然可以在Forge、NeoForge上加载Fabric模组，但稳定性太差了，而且至今也没有能在Spigot上运行的办法（我曾尝试修改，但奈何技术太差没改成）希望能够适配一下。

**Comment by AnzhiZhang** [comment]
什么平台，都要就慢慢等吧。另外请到插件仓库发 issue https://github.com/AnzhiZhang/MCDReforgedPlugins/tree/master/src/minecraft_command_register
